pipeline{
    agent any
    stages{
        stage("checkout stage"){
            steps{
                checkout scmGit(branches: [[name: '*/beanstalk-project']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/SivaSuribabu/elasticbeanstalk.git']])
            }
        }
    }
}