pipeline{
    agent any
    stages{
        stage("source code checkout"){
            steps{
                checkout scmGit(branches: [[name: '*/beanstalk-project']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/SivaSuribabu/elasticbeanstalk.git']])
                dir('blue-world-app'){
                    sh 'mvn clean package'
                }

            }
        }
    }
}