pipeline{
    agent any
    stages{
        stage("checkout stage"){
            echo "=====checkout stage====="
            steps{
                checkout scmGit(branches: [[name: '*/beanstalk-project']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/SivaSuribabu/elasticbeanstalk.git']])
            }
            echo "=====checkout stage completed====="
        }
        stage("build-stage"){
            when {
                expression { return false }
            }
            steps{
                sh "skipped"
            }
        }
    }
}